package org.bgr.model.db;

import io.quarkus.hibernate.orm.panache.PanacheEntityBase;
import org.hibernate.annotations.ColumnDefault;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.GenericGenerator;

import javax.enterprise.inject.Default;
import javax.persistence.*;
import java.time.LocalDateTime;
import java.util.UUID;

@Entity
@Table(name="file_container", indexes = {
        @Index(columnList = "id", name = "ndx_file_container_id"),
        @Index(columnList = "contextId", name = "ndx_file_container_contextId"),
        @Index(columnList = "t0", name = "ndx_file_container_t0"),
        @Index(columnList = "contextType", name = "ndx_file_container_contextType"),
        @Index(columnList = "rs", name = "ndx_file_container_rs")
    }
)
public class FileContainerModel extends PanacheEntityBase {
    @Id
    @GeneratedValue(generator = "UUID")
    @GenericGenerator(
            name = "UUID",
            strategy = "org.hibernate.id.UUIDGenerator"
    )
    @Column(name = "id", updatable = false, nullable = false)
    public UUID id;

    public UUID contextId;

    @CreationTimestamp
    public LocalDateTime t0;

    /*
    * 1 - users
    * 2 - power plant
    * 3 - power plant inspection protocol
    * 4 - investment
    * */
    public Integer contextType;

    /*
    * 11 = personal document
    * 14 = sepa
    * 20 = Verbrauchsabrechnung
    * 21 = Prognoserechnung
    * 22 = Projektierung
    * 26 = Galerie
    * 23 = Anschreiben
    * 24 = Vertrag Energieeinsparung
    * 25 = Vertrag Verrechnungsblatt
    * 27 = Vollmacht Abwicklung
    * 28 = Backend only files
    * 29 = Vollmacht Energieabrechnung
    * 291 = Vollmacht Netzbetreiber
    * 30 = Dach
    * 31 = Wechselrichter
    * 32 = Kabelverlegung
    * 33 = Einspeisepunkt
    * 34 = Warmwasserbereitung
    * 35 = Ladeinfrastruktur
     * */
    public Integer type;

    public Integer sortOrder;

    //!TODO parameters are only used on frontside for gui rendering
    //!TODO update backend functions to verify conditions!

    //generated by system after backend user trigger!
    @Column(nullable = false, columnDefinition = "boolean default false")
    public Boolean downloadOnly;

    @Column(nullable = false, columnDefinition = "boolean default false")
    public Boolean uploadOnly;

    @Column(nullable = false, columnDefinition = "boolean default false")
    public Boolean backendUploadOnly;

    @Column(nullable = false, columnDefinition = "boolean default false")
    public Boolean backendOnly;

    @Column(nullable = false, columnDefinition = "boolean default false")
    public Boolean noStatusUpdate;

    @Column(columnDefinition="TEXT")
    public String comment;

    //@ColumnDefault("0")
    public Integer rs;;
}
