export default [
  {
    title: 'Dashboard',
    route: 'home',
    icon: 'HomeIcon',
    resource: 'Dashboard',
    action: 'read',
  },
  {
    title: 'Kunden',
    route: 'users',
    icon: 'UsersIcon',
    resource: 'Users',
    action: 'read',
  },
  {
    title: 'Anlagen',
    route: 'power-plant-list',
    icon: 'ZapIcon',
    resource: 'SolarPlant',
    action: 'read',
  },
  {
    title: 'Anlagenabr.',
    icon: 'CreditCardIcon',
    resource: 'Dashboard',
    action: 'read',
    children: [
      {
        title: 'Liste',
        route: 'power-plant-repayment-list',
        icon: 'ListIcon',
        resource: 'Chat',
        action: 'read',
      },
      {
        title: 'Report',
        route: 'power-plant-repayment-report',
        icon: 'BookIcon',
        resource: 'Chat',
        action: 'read',
      },
    ],
  },
  {
    title: 'Investitionen',
    route: 'investment-list',
    icon: 'TrendingUpIcon',
    resource: 'Chat',
    action: 'read',
  },
  {
    title: 'WEB Nachrichten',
    route: 'web-info',
    icon: 'FileIcon',
    resource: 'Dashboard',
    action: 'read',
  },
  {
    title: 'Aktivitäten',
    route: 'activity',
    icon: 'ActivityIcon',
    resource: 'Dashboard',
    action: 'read',
  },
  {
    title: 'Einstellungen',
    icon: 'SettingsIcon',
    resource: 'Dashboard',
    action: 'read',
    children: [
      {
        title: 'Tarif',
        route: 'admin-settings-list',
        resource: 'Dashboard',
        action: 'read',
      },
      {
        title: 'Kampagne',
        route: 'admin-settings-list-campaign',
        resource: 'Dashboard',
        action: 'read',
      },
      {
        title: 'Zusatzleistungen',
        route: 'admin-settings-list-extras',
        resource: 'Dashboard',
        action: 'read',
      },
    ],
  },
  {
    title: 'Chat',
    route: 'apps-chat',
    icon: 'MessageSquareIcon',
    resource: 'Chat',
    action: 'read',
  },
]
